apiVersion: v1
kind: Service
metadata:
  name: np-svc
  labels:
     app: ng-persistente
spec:
  type: NodePort
  ports:
  - port: 80
    #nodePort: 30080
    protocol: TCP
  selector:
     app: ng-persistente